#!/usr/bin/env python

import sys
import argparse
from github_cli.commands import register_commands

def main():
    arg_parser = argparse.ArgumentParser()
    register_commands(arg_parser)
    args = arg_parser.parse_args(sys.argv[1:])
    command = args.command_class()
    command.execute(args)

if __name__ == "__main__":
    main()
